name: Update Snake

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Platane/snk@master
      with:
        github_user_name: clebercmsf
        github_token: ${{ secrets.github_token }}
        svg_out_path: dist/github-contribution-grid-snake.svg
